ALTER TABLE jobs ADD COLUMN started_at TIMESTAMP(6) WITH TIME ZONE;
ALTER TABLE jobs ADD COLUMN completed_at TIMESTAMP(6) WITH TIME ZONE;
ALTER TABLE jobs ADD COLUMN updated_at TIMESTAMP(6) WITH TIME ZONE;
